### ISSUE TITLE
A little help needed

### ISSUE THREAD

**Issue by vankofalcon** [Nerzal/gocloak#68]
I'm trying to add gocloak module to mine as a dependency but something strange happens. Can you please explain to me what I'm doing wrong and why this is the result?

1. add the import in my go file like this 

import "github.com/Nerzal/gocloak"

2. add this to my go.mod file

require github.com/Nerzal/gocloak v2.0.0

3. I build with go build and my go.mod file got overridden like this

require github.com/Nerzal/gocloak v0.0.0-20190525151100-dfd1e50572f8

**Comment by SVilgelm** [comment]
I have same problem and I'm not sure how to fix it, maybe we need to use go.mod for this.

**Comment by SVilgelm** [comment]
I tried to use gopkg.in instead of GitHub, but got an error:
gopkg.in/nerzal/gocloak.v2@v2.0.1: go.mod has non-....v2 module path "github.com/Nerzal/gocloak" at revision v2.0.1

Here is what I found by googling go.mod has non-....v2 module path:
* https://github.com/golang/go/issues/30636
* https://github.com/golang/go/issues/30831

**Comment by SVilgelm** [comment]
I created a bug in go repo: https://github.com/golang/go/issues/32332

**Comment by SVilgelm** [comment]
should be fixed in v3, PR #66

**Comment by Nerzal** [comment]
@vankofalcon 
Please check again with new V3 Version, if problem still exists

**Comment by SVilgelm** [comment]
Now it looks like: 	`github.com/Nerzal/gocloak/v3 v3.0.0-20190604083857-c59503a62409`

**Comment by SVilgelm** [comment]
I tested it, and the new version with v3.0.0 tag works as expected.

```go
module test

go 1.12

require github.com/Nerzal/gocloak/v3 v3.0.0
```
So I'm closing.

**Comment by vankofalcon** [comment]
thx @SVilgelm works like a charm :)

**Comment by dalu** [comment]
So how do you actually install it now?
My keycloak version is 6.0.1
Plain old github url or gopkg.in or what do I use?
I don't want to use go.mod because it fills the fs with duplicate crap.

**Comment by SVilgelm** [comment]
@dalu, take a look at this article: https://github.com/golang/go/wiki/Modules#when-do-i-get-old-behavior-vs-new-module-based-behavior

Also you can always clone the repo using ‘git clone’
By the way, go.mod makes a copy of repos with the specific versions, so it should not break other projects you have in $GOPATH

**Comment by dalu** [comment]
yes go mod uses up space unnecessarily. I don't want to argue about it, so don't try to preach.
I'm so tried of people trying to preach their way of doing things.
https://i.imgur.com/M2pcce8.jpg
End of discussion.
If you can't answer the question, don't bother replying.
You are acting condescending and insulting.

Meanwhile I used gopkg to go get and also to import.
The readme is wrong.

**Comment by Nerzal** [comment]
Noone is acting "insulting" especially not SVilgelm.
He answered the question. I also use gocloak WITHOUT go modules.

**Comment by SVilgelm** [comment]
:)
I have a question - what is wrong in readme?
